# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181011_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.Project'),
        ),
    ]
