# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181012_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='average',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
